### ISSUE TITLE
Ruby crash

### ISSUE THREAD

**Issue by ariccio** [learn-co-curriculum/js-beatles-loops-lab#34]
A syntax error caused `learn test` to crash:
```
// ♥ learn test

> js-beatles-loops-lab@0.1.0 test /home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001
> mocha -R mocha-multi --reporter-options nyan=-,json=.results.json

/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-core/lib/transformation/file/index.js:558
      throw err;
      ^

SyntaxError: /home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/index.js: "i" is read-only
  21 |     }
  22 |   const outArray = [];
> 23 |   for(const i = 0; i < n; i++) {
     |                           ^
  24 |     outArray.push("I love the Beatles!");
  25 |   }
  26 |   return outArray;
    at File.buildCodeFrameError (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-core/lib/transformation/file/index.js:427:15)
    at NodePath.buildCodeFrameError (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-traverse/lib/path/index.js:140:26)
    at PluginPass.Scope (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-plugin-check-es2015-constants/lib/index.js:35:29)
    at PluginPass.newFn (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-traverse/lib/visitors.js:318:17)
    at newFn (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-traverse/lib/index.js:114:17)
    at traverse (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-traverse/lib/index.js:79:12)
    at File.transform (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-core/lib/transformation/file/index.js:516:35)
    at /home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-core/lib/transformation/pipeline.js:50:19
    at File.wrap (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-core/lib/transformation/file/index.js:532:16)
    at Pipeline.transform (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
    at Object.transformFileSync (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/babel-core/lib/api/node.js:152:10)
    at Object.<anonymous> (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/test/root.js:7:27)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at /home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/mocha/lib/mocha.js:469:10)
    at Object.<anonymous> (/home/salubrious-routine-5028/js-beatles-loops-lab-bootcamp-prep-001/node_modules/mocha/bin/_mocha:404:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! Test failed.  See above for more details.
[21:05:12] (master) js-beatles-loops-lab-bootcamp-prep-001
// ♥ Traceback (most recent call last):
        11: from /usr/local/rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in`<main>'
        10: from /usr/local/rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in`eval'
         9: from /usr/local/rvm/gems/ruby-2.6.1/bin/learn-test:23:in `<main>'
         8: from /usr/local/rvm/gems/ruby-2.6.1/bin/learn-test:23:in `load'
         7: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/bin/learn-test:68:in `<top (required)>'
         6: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:20:in `run'
         5: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:20:in `fork'
         4: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:21:in `block in run'
         3: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:44:in `report_and_clean'
         2: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/reporter.rb:13:in `report'
         1: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/reporter.rb:47:in `report'
/usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/strategies/mocha.rb:42:in `results': undefined method `[]' for nil:NilClass (NoMethodError)
learn test^C
```

This should be cleanly [bubbled up](https://devblogs.microsoft.com/oldnewthing/20130219-00/?p=5203) to the user instead of causing the whole script to fly apart.

**Comment by maxwellbenton** [comment]
Hi there @ariccio! 

Thank you for this feedback. We have logged this and passed this feedback on to our engineering team.

Looking at the error you posted, it looks like this came from the `const` declared in the first statement. Since a constant can't be changed, this error is produced when the loop attempts to increment the variable. While the Learn tool is able to handle a variety of errors and code failures, it relies on the testing framework built into the lesson. Syntax errors like this are due to how JavaScript's variables work and will always cause the framework to crash. 

As this is feedback for the Learn tool and isn't an issue with this particular lesson, I am going to close this issue. If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can to clarify our error,
and we will try to find a fix. For more information, 
[check out this article on raising GitHub issues regarding Learn lessons][raise].

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
