### ISSUE TITLE
Issue with IDE

### ISSUE THREAD

**Issue by lfrankovich** [learn-co-curriculum/js-beatles-loops-lab#43]
I'm getting the following message and was wondering if there's something wrong with my code or with my computer. Thank you!

[21:04:52] ~
// ♥ learn open js-beatles-loops-lab-js-apply-000
Looking for lesson...
Forking lesson...
Cloning lesson...
Opening lesson...
Installing npm dependencies...
yarn install v1.19.1
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear thiswarning, remove package-lock.json.
[1/4] Resolving packages...
warning babel-core > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning babel-core > babel-register > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
warning jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check.Excluding it from installation.
[3/4] Linking dependencies...
warning " > mocha-multi@1.1.3" has incorrect peer dependency "mocha@>=2.2.0 <7.0.0".
[4/4] Building fresh packages...
warning Your current version of Yarn is out of date. The latest version is "1.22.4", while you're on "1.19.1".
info To upgrade, run the following command:
$ sudo apt-get update && sudo apt-get install yarn
Done in 7.51s.
Done.
[21:05:04] (master) js-beatles-loops-lab-js-apply-000
// ♥ learn

> js-beatles-loops-lab@0.1.0 test /home/empathetic-jest-3986/js-beatles-loops-lab-js-apply-000
> mocha -R mocha-multi --reporter-options spec=-,json=.results.json

(node:1044) DeprecationWarning: Configuration via mocha.opts is DEPRECATED and will be removed from a future version of Mocha. Use RC files or package.json instead.

**Comment by anickel101** [comment]
Hi, bumping this as I'm also having some major issues with the IDE. I get similar warnings to you when I start. When I run 'learn test', I pass (although for whatever reason, my "iLoveTheBeatles" function doesn't test). There seems to be a memory leak or something?

I can 'learn submit' just fine, but 'learn test' blows up.

Any advice?

// ♥ learn test

> js-beatles-loops-lab@0.1.0 test /home/anickel/js-beatles-loops-lab-bootcamp-prep-001
> mocha -R mocha-multi --reporter-options spec=-,json=.results.json

(node:1168) DeprecationWarning: Configuration via mocha.opts is DEPRECATED and will be removed from a future version of Mocha. Use RC files or package.json instead.


  theBeatlesPlay
    ✓ returns an array of strings containing what instruments each musician plays
    johnLennonFacts
      ✓ returns an array of strings with exclamation points
      ✓ takes in any array of strings and returns a new array with exclamation points added to each element
    iLoveTheBeatles

<--- Last few GCs --->

[1168:0x3331120]     3923 ms: Mark-sweep 607.1 (649.2) -> 607.1 (649.2) MB, 227.5 / 0.0 ms  allocation failure GC in old space requested
[1168:0x3331120]     4165 ms: Mark-sweep 607.1 (649.2) -> 607.0 (614.2) MB, 242.6 / 0.0 ms  last resort GC in old space requested
[1168:0x3331120]     4392 ms: Mark-sweep 607.0 (614.2) -> 607.0 (614.2) MB, 226.1 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x27ad1aca5891 <JSObject>
    1: iLoveTheBeatles(aka iLoveTheBeatles) [about:blank:~27] [pc=0xf2f18140cda](this=0xd1e24022d1 <undefined>,num=7)
    2: /* anonymous */ [/home/anickel/js-beatles-loops-lab-bootcamp-prep-001/test/index-test.js:29] [bytecode=0x75f4bfef1b1 offset=15](this=0x192cab3a3e11 <Context map = 0xfd42bc1d219>)
    3: callFn(aka callFn) [/home/anickel/js-beatles-loops-lab-bootcamp-prep-001/node_modules/m...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x8cd49c [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewUninitializedFixedArray(int) [node]
 6: 0xd84573 [node]
 7: v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 8: 0xf2f17f842fd
Aborted (core dumped)
npm ERR! Test failed.  See above for more details.
[15:54:42] (master) js-beatles-loops-lab-bootcamp-prep-001
// ♥ Traceback (most recent call last):
        11: from /usr/local/rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in`<main>'
        10: from /usr/local/rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in`eval'
         9: from /usr/local/rvm/gems/ruby-2.6.1/bin/learn-test:23:in `<main>'
         8: from /usr/local/rvm/gems/ruby-2.6.1/bin/learn-test:23:in `load'
         7: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/bin/learn-test:68:in `<top (required)>'
         6: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:20:in `run'
         5: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:20:in `fork'
         4: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:21:in `block in run'
         3: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:44:in `report_and_clean'
         2: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/reporter.rb:13:in `report'
         1: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/reporter.rb:47:in `report'
/usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/strategies/m

**Comment by anickel101** [comment]
nvm. my code was...poor. Great learning moment though.
